services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CPSIT\Typo3PersonioJobs\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Enums/*'
      - '../Classes/Exception/*'

  CPSIT\Typo3PersonioJobs\Cache\CacheManager:
    arguments:
      $pageCache: '@cache.pages'

  CPSIT\Typo3PersonioJobs\Command\ImportJobsCommand:
    arguments:
      $connection: '@connection.jobs'
    tags:
      - name: 'console.command'
        command: 'personio:import-jobs'
        description: 'Import jobs from Personio XML feed'

  CPSIT\Typo3PersonioJobs\Configuration\ExtensionConfiguration:
    public: true

  CPSIT\Typo3PersonioJobs\Hooks\DataHandlerHook:
    public: true

  cache.pages:
    class: 'TYPO3\CMS\Core\Cache\Frontend\FrontendInterface'
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments:
      - 'pages'

  connection.jobs:
    class: 'TYPO3\CMS\Core\Database\Connection'
    factory: ['@TYPO3\CMS\Core\Database\ConnectionPool', 'getConnectionForTable']
    arguments:
      - !php/const CPSIT\Typo3PersonioJobs\Domain\Model\Job::TABLE_NAME
