services:
  _defaults:
    autowire: true
    autoconfigure: true

  CPSIT\Typo3PersonioJobs\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Enums/*'
      - '../Classes/Exception/*'
