name: CGL
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cgl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          # @todo Use PHP 8.4 once PHP-CS-Fixer supports PHP 8.4
          php-version: 8.3
          tools: composer:v2, composer-require-checker, composer-unused
          coverage: none

      # Validation
      - name: Validate composer.json
        run: composer validate --no-check-lock

      # Install dependencies
      - name: Install Composer dependencies
        run: |
          composer require --no-progress --no-plugins brotkrueml/schema:"^2.7 || ^3.0"

      # Check Composer dependencies
      - name: Check dependencies
        run: composer-require-checker check
      - run: composer install --no-progress
      - name: Check for unused dependencies
        run: composer-unused

      # Linting
      - name: Lint composer.json
        run: composer lint:composer
      - name: Lint Editorconfig
        run: composer lint:editorconfig
      - name: Lint PHP
        run: composer lint:php
      - name: Lint TypoScript
        run: composer lint:typoscript -- --fail-on-warnings

      # SCA
      - name: SCA PHP
        run: composer sca:php -- --error-format github

      # Migration
      - name: Run Rector migration
        run: composer migration:rector -- --dry-run
